name: Deploy Pipeline

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate code
        run: echo "Validando archivos... build exitoso ✅"

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        run: echo "Desplegando a STAGING automáticamente 🚀"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to production
        run: echo "Desplegando a PRODUCTION tras aprobación ✅"
